# Generated by Django 4.2.6 on 2023-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='Auth',
        ),
    ]
