# Generated by Django 4.2.6 on 2023-11-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_main_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
