# Generated by Django 4.2.6 on 2023-11-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AddField(
            model_name='entry',
            name='holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
