# Generated by Django 4.2.6 on 2023-11-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_entry_is_starred_alter_entry_content_and_more'),
    ]

    operations = [
    ]
